Document: deb-pkg-tut
Title: Debian deb-pkg-tut Manual
Author: <insert document author here>
Abstract: This manual describes what deb-pkg-tut is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deb-pkg-tut/deb-pkg-tut.sgml.gz

Format: postscript
Files: /usr/share/doc/deb-pkg-tut/deb-pkg-tut.ps.gz

Format: text
Files: /usr/share/doc/deb-pkg-tut/deb-pkg-tut.text.gz

Format: HTML
Index: /usr/share/doc/deb-pkg-tut/html/index.html
Files: /usr/share/doc/deb-pkg-tut/html/*.html
